apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: go-metrics
  name: go-metrics
  namespace: prometheus
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: go-metrics
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: go-metrics
    spec:
      containers:
      - image: docker.io/joewalker/go-metrics
        imagePullPolicy: Always
        name: go-metrics
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          limits:
            cpu: 50m
            memory: 32Mi
          requests:
            cpu: 50m
            memory: 32Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
