apiVersion: v1
kind: Service
metadata:
  name: go-metrics
  namespace: prometheus
spec:
  selector:
    app: go-metrics
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP